### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create html skeleton
- [x] insert a transparent top down image of a car
- [x] ensure that the form looks nice on both mobile-sized and desktop-sized screens.
