### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Use CSS transform to turn car in four directions:
  - [x] north.
  - [x] south
  - [x] east
  - [x] west
- [x] Create a data model that includes which way the car is facing, (north, south, east, or west)
- [x] Query the document 
- [x] Listen for 'keydown' events on the document
- [x] Make a callback function that changes the car image's class according to which direction it is being turned.
  - [x] Query the car image
  - [x] Make conditionals for each arrow key
  - [x] Store the car's direction in the data model
- [x] Test functionality
- [x] Fix all errors
